// Package declaration for the Gym System views
package com.gym.view;
// Import statements for necessary classes and utilities

import com.gym.model.GymModel;
import com.gym.util.ValidationUtil;
import java.awt.Color;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anish Shrestha 23048634
 */
public class AdminPanel extends javax.swing.JFrame {

    private final List<GymModel> memberList = new LinkedList();

    /**
     * Constructor for the AdminPanel class. Initializes the panel components,
     * hides the table panel by default, and populates the member list with
     * initial data.
     */
    public AdminPanel() {
        initComponents();
        pnlTable.setVisible(false);
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        pnlAddMemberMain = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        lblAmountToPay = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblMobileNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblMemberId = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        cbGymTime = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        lblGymTime = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        tfAmountToPay = new javax.swing.JTextField();
        tfMobileNumber = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        tfAge = new javax.swing.JTextField();
        tfMemberId = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        btnViewTable = new javax.swing.JButton();
        lblErrorId = new javax.swing.JLabel();
        lblErrorAge = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorFee = new javax.swing.JLabel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorGender = new javax.swing.JLabel();
        lblErrorName = new javax.swing.JLabel();
        btnUpdateMain = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblAddMemberIcon = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        spMemberTable = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnUpdateList = new javax.swing.JButton();
        btnDeleteMember = new javax.swing.JButton();
        lblListOfMemberIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 42));
        setMaximumSize(new java.awt.Dimension(1900, 963));
        setMinimumSize(new java.awt.Dimension(1900, 963));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1900, 963));
        setResizable(false);

        pnlAddMemberMain.setBackground(new java.awt.Color(0, 0, 0));
        pnlAddMemberMain.setMaximumSize(new java.awt.Dimension(1900, 963));
        pnlAddMemberMain.setMinimumSize(new java.awt.Dimension(1900, 963));
        pnlAddMemberMain.setPreferredSize(new java.awt.Dimension(1900, 963));
        pnlAddMemberMain.setLayout(null);

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setFocusPainted(false);
        btnSave.setFocusable(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlAddMemberMain.add(btnSave);
        btnSave.setBounds(80, 640, 110, 40);

        lblAmountToPay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAmountToPay.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountToPay.setText("Amount to pay:");
        pnlAddMemberMain.add(lblAmountToPay);
        lblAmountToPay.setBounds(70, 500, 118, 22);

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAge.setForeground(java.awt.Color.white);
        lblAge.setText("Age:");
        pnlAddMemberMain.add(lblAge);
        lblAge.setBounds(70, 330, 50, 30);

        tfEmail.setBackground(new java.awt.Color(0, 0, 0,100));
        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfEmail);
        tfEmail.setBounds(200, 410, 190, 40);

        lblMobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMobileNumber.setForeground(java.awt.Color.white);
        lblMobileNumber.setText("Mobile Number:");
        pnlAddMemberMain.add(lblMobileNumber);
        lblMobileNumber.setBounds(570, 180, 125, 22);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName.setForeground(java.awt.Color.white);
        lblName.setText("Name:");
        pnlAddMemberMain.add(lblName);
        lblName.setBounds(70, 250, 50, 30);

        tfName.setBackground(new java.awt.Color(0, 0, 0,100));
        tfName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfName);
        tfName.setBounds(200, 250, 190, 40);

        lblMemberId.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMemberId.setForeground(java.awt.Color.white);
        lblMemberId.setText("Member Id:");
        pnlAddMemberMain.add(lblMemberId);
        lblMemberId.setBounds(70, 180, 87, 22);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmail.setForeground(java.awt.Color.white);
        lblEmail.setText("Email:");
        pnlAddMemberMain.add(lblEmail);
        lblEmail.setBounds(70, 420, 47, 22);

        cbGymTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5:00AM-11:00AM", "4:00PM-8:00PM" }));
        pnlAddMemberMain.add(cbGymTime);
        cbGymTime.setBounds(720, 330, 150, 40);

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGender.setForeground(java.awt.Color.white);
        lblGender.setText("Gender:");
        pnlAddMemberMain.add(lblGender);
        lblGender.setBounds(570, 250, 59, 22);

        lblGymTime.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGymTime.setForeground(java.awt.Color.white);
        lblGymTime.setText("Gym Time:");
        pnlAddMemberMain.add(lblGymTime);
        lblGymTime.setBounds(570, 350, 81, 20);

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(204, 0, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setFocusPainted(false);
        btnReset.setFocusable(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlAddMemberMain.add(btnReset);
        btnReset.setBounds(190, 640, 130, 40);

        tfAmountToPay.setBackground(new java.awt.Color(0, 0, 0,100));
        tfAmountToPay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfAmountToPay.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfAmountToPay);
        tfAmountToPay.setBounds(200, 490, 190, 40);

        tfMobileNumber.setBackground(new java.awt.Color(0, 0, 0,100));
        tfMobileNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfMobileNumber);
        tfMobileNumber.setBounds(720, 170, 190, 40);

        genderGroup.add(rbMale);
        rbMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        pnlAddMemberMain.add(rbMale);
        rbMale.setBounds(720, 250, 60, 25);

        genderGroup.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        pnlAddMemberMain.add(rbFemale);
        rbFemale.setBounds(810, 250, 70, 25);

        tfAge.setBackground(new java.awt.Color(0, 0, 0,100));
        tfAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfAge.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfAge);
        tfAge.setBounds(200, 330, 190, 40);

        tfMemberId.setBackground(new java.awt.Color(0, 0, 0,100));
        tfMemberId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfMemberId.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfMemberId);
        tfMemberId.setBounds(200, 170, 190, 40);

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAddress.setForeground(java.awt.Color.white);
        lblAddress.setText("Address");
        pnlAddMemberMain.add(lblAddress);
        lblAddress.setBounds(570, 420, 81, 20);

        tfAddress.setBackground(new java.awt.Color(0, 0, 0,100));
        tfAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfAddress.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddMemberMain.add(tfAddress);
        tfAddress.setBounds(720, 410, 190, 40);

        btnViewTable.setBackground(new java.awt.Color(0, 0, 0));
        btnViewTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewTable.setForeground(new java.awt.Color(204, 0, 0));
        btnViewTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/list of members.png"))); // NOI18N
        btnViewTable.setText("View Table");
        btnViewTable.setBorderPainted(false);
        btnViewTable.setContentAreaFilled(false);
        btnViewTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewTable.setFocusPainted(false);
        btnViewTable.setFocusable(false);
        btnViewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTableActionPerformed(evt);
            }
        });
        pnlAddMemberMain.add(btnViewTable);
        btnViewTable.setBounds(320, 640, 180, 40);

        lblErrorId.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorId);
        lblErrorId.setBounds(200, 220, 190, 20);

        lblErrorAge.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorAge);
        lblErrorAge.setBounds(200, 380, 190, 20);

        lblErrorEmail.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorEmail);
        lblErrorEmail.setBounds(200, 460, 200, 20);

        lblErrorFee.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorFee);
        lblErrorFee.setBounds(200, 540, 190, 20);

        lblErrorPhone.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorPhone);
        lblErrorPhone.setBounds(720, 220, 190, 20);

        lblErrorAddress.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorAddress);
        lblErrorAddress.setBounds(720, 460, 190, 20);

        lblErrorGender.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorGender);
        lblErrorGender.setBounds(720, 290, 170, 20);

        lblErrorName.setForeground(new java.awt.Color(255, 255, 0));
        pnlAddMemberMain.add(lblErrorName);
        lblErrorName.setBounds(200, 300, 190, 20);

        btnUpdateMain.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateMain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateMain.setForeground(new java.awt.Color(204, 0, 0));
        btnUpdateMain.setText("Update");
        btnUpdateMain.setBorderPainted(false);
        btnUpdateMain.setContentAreaFilled(false);
        btnUpdateMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateMain.setFocusPainted(false);
        btnUpdateMain.setFocusable(false);
        btnUpdateMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMainActionPerformed(evt);
            }
        });
        pnlAddMemberMain.add(btnUpdateMain);
        btnUpdateMain.setBounds(490, 640, 130, 40);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlAddMemberMain.add(btnExit);
        btnExit.setBounds(1840, 0, 60, 30);

        lblAddMemberIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/adminPanelIcon.png"))); // NOI18N
        lblAddMemberIcon.setText("jLabel10");
        pnlAddMemberMain.add(lblAddMemberIcon);
        lblAddMemberIcon.setBounds(0, 0, 2308, 970);

        pnlTable.setMaximumSize(new java.awt.Dimension(1900, 963));
        pnlTable.setMinimumSize(new java.awt.Dimension(1900, 963));
        pnlTable.setPreferredSize(new java.awt.Dimension(1900, 963));
        pnlTable.setLayout(null);

        spMemberTable.setBackground(new java.awt.Color(204, 204, 204));

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id", "Name", "Number", "Age", "Gender", "Email", "Address", "GymTime", "Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMember.setRowHeight(30);
        tblMember.getTableHeader().setReorderingAllowed(false);
        spMemberTable.setViewportView(tblMember);
        if (tblMember.getColumnModel().getColumnCount() > 0) {
            tblMember.getColumnModel().getColumn(0).setResizable(false);
            tblMember.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblMember.getColumnModel().getColumn(1).setResizable(false);
            tblMember.getColumnModel().getColumn(2).setResizable(false);
            tblMember.getColumnModel().getColumn(3).setResizable(false);
            tblMember.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblMember.getColumnModel().getColumn(4).setResizable(false);
            tblMember.getColumnModel().getColumn(4).setPreferredWidth(15);
            tblMember.getColumnModel().getColumn(5).setResizable(false);
            tblMember.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblMember.getColumnModel().getColumn(6).setResizable(false);
            tblMember.getColumnModel().getColumn(7).setResizable(false);
            tblMember.getColumnModel().getColumn(8).setResizable(false);
            tblMember.getColumnModel().getColumn(8).setPreferredWidth(15);
        }

        pnlTable.add(spMemberTable);
        spMemberTable.setBounds(250, 260, 1450, 530);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 51));
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlTable.add(btnBack);
        btnBack.setBounds(1560, 50, 100, 40);

        btnUpdateList.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateList.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdateList.setText("Update Selected Row");
        btnUpdateList.setBorder(null);
        btnUpdateList.setBorderPainted(false);
        btnUpdateList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateList.setFocusPainted(false);
        btnUpdateList.setFocusable(false);
        btnUpdateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateListActionPerformed(evt);
            }
        });
        pnlTable.add(btnUpdateList);
        btnUpdateList.setBounds(320, 830, 180, 30);

        btnDeleteMember.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteMember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteMember.setForeground(new java.awt.Color(255, 0, 0));
        btnDeleteMember.setText("Delete Selected Row");
        btnDeleteMember.setBorder(null);
        btnDeleteMember.setBorderPainted(false);
        btnDeleteMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteMember.setFocusPainted(false);
        btnDeleteMember.setFocusable(false);
        btnDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMemberActionPerformed(evt);
            }
        });
        pnlTable.add(btnDeleteMember);
        btnDeleteMember.setBounds(550, 830, 180, 30);

        lblListOfMemberIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/listOfmemberIcon.png"))); // NOI18N
        lblListOfMemberIcon.setText("jLabel2");
        pnlTable.add(lblListOfMemberIcon);
        lblListOfMemberIcon.setBounds(0, 10, 2163, 963);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddMemberMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAddMemberMain, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void initializeData() {
        registerMember(new GymModel(1, "Laura Chen", (short) 21, "laurachen@gmail.com", "9849895698", "female", "5:00AM-11:00AM", 6000, "Lalitpur"));
        registerMember(new GymModel(2, "Gerry Arno", (short) 24, "gerryarno@gmail.com", "9847895298", "male", "5:00AM-11:00AM", 12000, "Bhaktapur"));
        registerMember(new GymModel(3, "alison Burgers", (short) 27, "alison@gmail.com", "9859895648", "male", "5:00AM-11:00AM", 6000, "Lalitpur"));
        registerMember(new GymModel(4, "Chen Ming", (short) 30, "chenming@gmail.com", "9849695740", "male", "6:00AM-12:00PM", 7500, "Kathmandu"));
        registerMember(new GymModel(5, "Liu Fang", (short) 25, "liufang@gmail.com", "9847564321", "female", "6:00AM-12:00PM", 8000, "Patan"));
        registerMember(new GymModel(6, "Yang Chen", (short) 22, "yangchen@gmail.com", "9856543210", "male", "6:00AM-12:00PM", 7000, "Bhaktapur"));
        registerMember(new GymModel(7, "Xiao Chen", (short) 28, "xiaozhao@gmail.com", "9845213245", "female", "6:00AM-12:00PM", 8500, "Lalitpur"));
        registerMember(new GymModel(8, "John Smith", (short) 22, "johnsmith@gmail.com", "9849895698", "male", "5:00AM-11:00AM", 6000, "Patan"));
        registerMember(new GymModel(9, "Emily Johnson", (short) 25, "emilyjohnson@gmail.com", "9847895298", "female", "5:00AM-11:00AM", 12000, "Bhaktapur"));
        registerMember(new GymModel(10, "Michael Brown", (short) 28, "michaelbrown@gmail.com", "9859895648", "male", "5:00AM-11:00AM", 7000, "Lalitpur"));
    }

    /**
     * Registers a new member by adding their information to the member list and
     * updating the JTable. The member's details are added to both the internal
     * member list and displayed in the table.
     *
     * @param member The GymModel object representing the new member to be
     * added.
     */
    void registerMember(GymModel member) {
        memberList.add(member);// Adds the member to the member list.
        DefaultTableModel model = (DefaultTableModel) tblMember.getModel(); // Retrieves the current table model of the JTable.

        // Adds a new row to the JTable with the member's details.
        model.addRow(new Object[]{member.getMemberId(),
            member.getName(), member.getNumber(), member.getAge(),
            member.getGender(), member.getEmail(), member.getAddress(),
            member.getGymTime(), member.getAmount()
        });
    }

    /**
     * Event handler for the Save button. Validates the user input, checks for
     * duplicates, and registers a new member if the input is valid.
     *
     * 1. Validates input fields such as member ID, name, email, phone number,
     * and age. 2. If all fields are valid, a new GymModel object is created. 3.
     * Checks for duplicate member IDs before adding the new member. 4. Displays
     * a success message upon successful registration or an error if validation
     * fails.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean isValid = true;
        // Retrieving input values from text fields and radio buttons
        String memberId = tfMemberId.getText();
        String name = tfName.getText();
        String email = tfEmail.getText();
        String phone = tfMobileNumber.getText();
        String gender = rbMale.isSelected() ? "male" : (rbFemale.isSelected() ? "female" : "");
        String fee = tfAmountToPay.getText();
        String address = tfAddress.getText();
        String time = (String) cbGymTime.getSelectedItem();
        // Validating input fields using helper method
        isValid &= validateField(lblErrorGender, "Please select", ValidationUtil.validateGender(gender));
        isValid &= validateField(lblErrorId, tfMemberId, "It must be a numeric value", ValidationUtil.validateId(memberId));
        isValid &= validateField(lblErrorName, tfName, "Name cannot contain number", ValidationUtil.validateName(name));
        isValid &= validateField(lblErrorEmail, tfEmail, "Please enter a valid email address", ValidationUtil.validateEmail(email));
        isValid &= validateField(lblErrorPhone, tfMobileNumber, "start with 98 and have 10 digits", ValidationUtil.validatePhone(phone));
        isValid &= validateField(lblErrorAddress, tfAddress, "Only character is allowed", ValidationUtil.validateName(address));
        isValid &= validateField(lblErrorFee, tfAmountToPay, "numeric value starts from 1000", ValidationUtil.validateFee(fee));
        // Validating age field
        try {
            short age = Short.parseShort(tfAge.getText().trim());
            if (age < 18 || age > 59) {
                lblErrorAge.setText("must be between 18 to 59");
                tfAge.setBackground(Color.RED);
                isValid = false;
            } else {
                tfAge.setBackground(new java.awt.Color(0, 0, 0, 100));
                lblErrorAge.setVisible(false);
            }
        } catch (NumberFormatException e) {
            tfAge.setBackground(Color.RED);
            lblErrorAge.setText("must a numeric value");
            isValid = false;
        }
// If validation passes, create a new GymModel object and register the member
        if (isValid) {
            GymModel newMember = new GymModel(Integer.parseInt(memberId), name, Short.parseShort(tfAge.getText()), email, phone, gender, time, Integer.parseInt(fee), address);
            // Check if the member ID already exists
            if (checkDuplicateId(newMember)) {
                lblErrorId.setText("Duplicate Member Id");
                lblErrorId.setVisible(true);
                tfMemberId.setBackground(Color.RED);

            } else {
                // Register the new member
                registerMember(newMember);
                JOptionPane.showMessageDialog(null, "Student added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnSaveActionPerformed
    /**
     * Event handler for the Reset button. Clears all the input fields and
     * resets the gender selection.
     *
     * 1. Clears the text fields for name, age, member ID, email, amount to pay,
     * and mobile number. 2. Resets the gender selection (unselects any selected
     * gender radio button).
     *
     * This method is useful for clearing the form for a new entry or to reset
     * after an invalid submission.
     *
     * @param evt The ActionEvent triggered by the Reset button click.
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfName.setText("");
        tfAge.setText("");
        tfMemberId.setText("");
        tfEmail.setText("");
        tfAmountToPay.setText("");
        tfMobileNumber.setText("");
        genderGroup.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed
    /**
     * Event handler for the "View Table" button. This method is triggered when
     * the user clicks the "View Table" button to display the member list.
     *
     * 1. Makes the table panel visible, so users can view the list of members.
     * 2. Hides the "Add Member" panel to ensure only the member list table is
     * visible.
     *
     * This is useful when the user wants to switch from adding a new member to
     * viewing the existing member data.
     *
     * @param evt The ActionEvent triggered by the "View Table" button click.
     */
    private void btnViewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTableActionPerformed
        // TODO add your handling code here:
        pnlTable.setVisible(true);
        pnlAddMemberMain.setVisible(false);
    }//GEN-LAST:event_btnViewTableActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        pnlTable.setVisible(false);
        pnlAddMemberMain.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * Event handler for the "Update List" button. This method is triggered when
     * the user selects a row in the table to update the corresponding member
     * details.
     *
     * 1. Retrieves the data from the selected row in the table. 2. Populates
     * the form fields with the selected member's details for updating. 3.
     * Switches the UI view from the table to the "Add Member" panel, allowing
     * the user to modify the member data.
     *
     * This method enables the user to select an existing member from the table
     * and edit their information.
     *
     * @param evt The ActionEvent triggered by the "Update List" button click.
     */
    private void btnUpdateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateListActionPerformed
        // Get data of the selected row
        String[] selectedRowData = getSelectedRowData();
        if (selectedRowData != null) {
            // Example: Access specific fields
            String memberId = selectedRowData[0];
            String name = selectedRowData[1];
            String phone = selectedRowData[2];
            String age = selectedRowData[3];
            String gender = selectedRowData[4];
            String email = selectedRowData[5];
            String address = selectedRowData[6];
            String gymTime = selectedRowData[7];
            String fee = selectedRowData[8];
            tfName.setText(name);
            tfAge.setText(age);
            tfMemberId.setText(memberId);
            tfEmail.setText(email);
            tfAmountToPay.setText(fee);
            tfMobileNumber.setText(phone);
            tfAddress.setText(address);
            cbGymTime.setSelectedItem(gymTime);
            if (gender.equalsIgnoreCase("male")) {
                rbMale.setSelected(true);
            } else {
                rbFemale.setSelected(true);
            }
            pnlTable.setVisible(false);
            pnlAddMemberMain.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateListActionPerformed
    /**
     * Retrieves the data from the currently selected row in the JTable.
     *
     * 1. Checks if a row is selected in the table. 2. If a row is selected, it
     * fetches the data for all columns in that row. 3. The row data is stored
     * in a String array and returned. 4. If no row is selected, an error
     * message is displayed, and null is returned.
     *
     * @return A String array containing the data of the selected row, or null
     * if no row is selected.
     */
    private String[] getSelectedRowData() {
        // Get the selected row index
        int selectedRow = tblMember.getSelectedRow();

        if (selectedRow != -1) { // Check if a row is selected
            DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
            int columnCount = model.getColumnCount();

            // Create an array to store the row data
            String[] rowData = new String[columnCount];

            // Iterate through the columns to get the selected row's data
            for (int col = 0; col < columnCount; col++) {
                Object value = model.getValueAt(selectedRow, col); //Get value at [selectedRow, col]
                rowData[col] = value.toString();
            }
            return rowData; // Return the selected row data
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Error", JOptionPane.ERROR_MESSAGE);
            return null; // No row selected
        }
    }

    /**
     * Event handler for the "Delete Member" button.
     *
     * This method performs the following actions when the delete button is
     * clicked: 1. Checks if a row is selected in the JTable. 2. If a row is
     * selected, it prompts the user for confirmation to delete the member. 3.
     * If the user confirms, it calls the `deleteSelectedData` method to remove
     * the member from the table. 4. Displays a success message if the deletion
     * was successful, or an error message if no row was selected.
     *
     * @param evt The ActionEvent associated with the delete button click.
     */
    private void btnDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMemberActionPerformed
        /// TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
        int selectedRow = tblMember.getSelectedRow();

        if (selectedRow != -1) { // Check if a row is selected
            // Extract row data
            int id = (Integer) tblMember.getValueAt(selectedRow, 0);
            int confirm = JOptionPane.showConfirmDialog(
                    null, // Parent component
                    "Are you sure you want to delete this member?", // Message
                    "Confirm Deletion", // Title
                    JOptionPane.YES_NO_OPTION, // Options
                    JOptionPane.WARNING_MESSAGE // Message type
            );
            if (confirm == JOptionPane.YES_OPTION) {
                boolean deleted = deleteSelectedData(id, selectedRow);
                if (deleted) {
                    JOptionPane.showMessageDialog(null, "Member deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a member to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMemberActionPerformed
    /**
     * Event handler for the "Update Member" button.
     *
     * This method performs the following actions when the update button is
     * clicked: 1. Validates the input fields (name, email, phone, gender, age,
     * etc.) to ensure they meet the required criteria. 2. If all fields are
     * valid, it searches for the member in the list based on the member ID. 3.
     * If the member is found, their details are updated with the new values
     * entered in the input fields. 4. After successfully updating the member,
     * the table is refreshed to show the updated data. 5. If no member is found
     * with the given ID, an error message is displayed.
     *
     * @param evt The ActionEvent associated with the update button click.
     */
    private void btnUpdateMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMainActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        String memberId = tfMemberId.getText();
        String name = tfName.getText();
        String email = tfEmail.getText();
        String phone = tfMobileNumber.getText();
        String gender = rbMale.isSelected() ? "male" : (rbFemale.isSelected() ? "female" : "");
        String fee = tfAmountToPay.getText();
        String address = tfAddress.getText();
        String time = (String) cbGymTime.getSelectedItem();

        isValid &= validateField(lblErrorGender, "Please select", ValidationUtil.validateGender(gender));
        isValid &= validateField(lblErrorId, tfMemberId, "It must be a numeric value", ValidationUtil.validateId(memberId));
        isValid &= validateField(lblErrorName, tfName, "Name cannot contain number", ValidationUtil.validateName(name));
        isValid &= validateField(lblErrorEmail, tfEmail, "Please enter a valid email address", ValidationUtil.validateEmail(email));
        isValid &= validateField(lblErrorPhone, tfMobileNumber, "start with 98 and have 10 digits", ValidationUtil.validatePhone(phone));
        isValid &= validateField(lblErrorAddress, tfAddress, "Only character is allowed", ValidationUtil.validateName(address));
        isValid &= validateField(lblErrorFee, tfAmountToPay, "numeric value starts from 1000", ValidationUtil.validateFee(fee));

        try {
            short age = Short.parseShort(tfAge.getText().trim());
            if (age < 18 || age > 59) {
                lblErrorAge.setText("must be between 18 to 59");
                tfAge.setBackground(Color.RED);
                isValid = false;
            } else {
                tfAge.setBackground(new java.awt.Color(0, 0, 0, 100));
                lblErrorAge.setVisible(false);
            }
        } catch (NumberFormatException e) {
            tfAge.setBackground(Color.RED);
            lblErrorAge.setText("must a numeric value");
            isValid = false;
        }
        if (isValid) {
            // Locate the member in the LinkedList and update it
            for (GymModel member : memberList) {
                if (member.getMemberId() == Integer.parseInt(memberId)) { // Matching memberId
                    // Update member details
                    member.setName(name);
                    member.setEmail(email);
                    member.setNumber(phone);
                    member.setGender(gender);
                    member.setAge(Short.parseShort(tfAge.getText()));
                    member.setAmount(Integer.parseInt(fee));
                    member.setAddress(address);
                    member.setGymTime(time);
                    loadMemberDataToTable();
                    JOptionPane.showMessageDialog(null, "Member updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    return; // Exit after updating
                }
            }

            // If no member found with the provided ID, show an error message
            JOptionPane.showMessageDialog(null, "No member found with the given ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateMainActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Loads the member data from the `memberList` into the JTable.
     *
     * This method performs the following actions: 1. Clears the existing rows
     * in the table to prepare for new data. 2. Iterates through the
     * `memberList` and adds each member's data as a new row in the JTable. 3.
     * Each row contains information such as the member's ID, name, phone
     * number, age, gender, email, address, gym time, and amount to be paid.
     *
     * The table is updated to reflect the current state of the `memberList`
     * after adding, removing, or updating members.
     */
    private void loadMemberDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tblMember.getModel();

        // Clear the table before loading new data
        model.setRowCount(0);

        // Iterate through the LinkedList and add each member to the table
        for (GymModel member : memberList) {
            model.addRow(new Object[]{
                member.getMemberId(),
                member.getName(),
                member.getNumber(),
                member.getAge(),
                member.getGender(),
                member.getEmail(),
                member.getAddress(),
                member.getGymTime(),
                member.getAmount()
            });
        }
    }

    /**
     * Validates a form field based on a given validation condition and updates
     * the UI accordingly.
     *
     * This method checks if the provided field is valid according to the
     * specified condition (`isValidFormat`). If the field is invalid, it
     * updates the background color of the text field to red and shows an error
     * message. If the field is valid, it resets the background color and hides
     * the error message.
     *
     * @param errorLbl The label that displays the error message.
     * @param errorField The text field to be validated.
     * @param errorMsg The error message to be shown if the validation fails.
     * @param isValidFormat The boolean condition indicating whether the field
     * is valid or not.
     * @return `true` if the field is valid, `false` otherwise.
     */
    private boolean validateField(JLabel errorLbl, JTextField errorField, String errorMsg, boolean isValidFormat) {
        if (!isValidFormat) {
            errorLbl.setText(errorMsg);
            errorField.setBackground(Color.RED);
            errorLbl.setVisible(true);
            return false;
        } else {
            errorField.setBackground(new java.awt.Color(0, 0, 0, 100));
            errorLbl.setVisible(false);
            return true;
        }
    }

    /**
     * Validates a form field based on a given validation condition and updates
     * the error label accordingly.
     *
     * This method checks if the provided field is valid according to the
     * specified condition (`isValidFormat`). If the field is invalid, it
     * displays an error message in the provided error label. If the field is
     * valid, it hides the error label.
     *
     * @param errorLbl The label that displays the error message.
     * @param errorMsg The error message to be shown if the validation fails.
     * @param isValidFormat The boolean condition indicating whether the field
     * is valid or not.
     * @return `true` if the field is valid, `false` otherwise.
     */
    private boolean validateField(JLabel errorLbl, String errorMsg, boolean isValidFormat) {
        if (!isValidFormat) {
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            errorLbl.setVisible(false);
            return true;
        }
    }

    /**
     * Checks if a member with the same member ID already exists in the member
     * list.
     *
     * This method iterates through the `memberList` and compares the provided
     * member's ID with the IDs of existing members. If a match is found, it
     * returns `true`, indicating a duplicate member ID. Otherwise, it returns
     * `false`.
     *
     * @param member The `GymModel` object containing the member details to be
     * checked.
     * @return `true` if a member with the same ID already exists, `false`
     * otherwise.
     */
    private boolean checkDuplicateId(GymModel member) {
        for (GymModel existingMember : memberList) {
            if (existingMember.getMemberId() == member.getMemberId()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Deletes the selected member from the member list and the table.
     *
     * This method searches for the member with the specified ID in the
     * `memberList` and removes the corresponding member. It also removes the
     * corresponding row from the JTable using the `selectedRow` index. If the
     * deletion is successful, it returns `true`; otherwise, it returns `false`
     * if no member is found with the given ID.
     *
     * @param id The ID of the member to be deleted.
     * @param selectedRow The row index of the member to be deleted in the
     * JTable.
     * @return `true` if the member was deleted successfully, `false` otherwise.
     */
    private boolean deleteSelectedData(int id, int selectedRow) {
        Iterator<GymModel> iterator = memberList.iterator();
        while (iterator.hasNext()) {
            GymModel member = iterator.next();
            if (member.getMemberId() == id) {
                // Remove the member from the list
                iterator.remove();

                // Also remove the row from the table
                DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
                model.removeRow(selectedRow);
                return true; // Member deleted successfully
            }
        }
        return false; // No member found with the given ID
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteMember;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateList;
    private javax.swing.JButton btnUpdateMain;
    private javax.swing.JButton btnViewTable;
    private javax.swing.JComboBox<String> cbGymTime;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel lblAddMemberIcon;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAmountToPay;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorAge;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFee;
    private javax.swing.JLabel lblErrorGender;
    private javax.swing.JLabel lblErrorId;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGymTime;
    private javax.swing.JLabel lblListOfMemberIcon;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlAddMemberMain;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JScrollPane spMemberTable;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfAmountToPay;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfMemberId;
    private javax.swing.JTextField tfMobileNumber;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
