// Package declaration for the Gym System views
package com.gym.view;

/**
 *
 * @author Anish Shrestha 23048634
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashBoard = new javax.swing.JPanel();
        pnlShowNewMember = new javax.swing.JPanel();
        lblNewMemberTitle = new javax.swing.JLabel();
        lblNewMemberName = new javax.swing.JLabel();
        lblIconNewMember = new javax.swing.JLabel();
        pnlShowRevenue = new javax.swing.JPanel();
        lblRevenueTitle = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        lblIconMoney = new javax.swing.JLabel();
        pnlShowTotalMember = new javax.swing.JPanel();
        lblTotalMemberTitle = new javax.swing.JLabel();
        lblTotalMember = new javax.swing.JLabel();
        lblTotalMemberIcon = new javax.swing.JLabel();
        pnlShowUPcomingEvents = new javax.swing.JPanel();
        lblUpcomingEventTitle = new javax.swing.JLabel();
        lblEventName = new javax.swing.JLabel();
        lblEventIcon = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblDashBoardIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 42));
        setMaximumSize(new java.awt.Dimension(1900, 963));
        setMinimumSize(new java.awt.Dimension(1900, 963));
        setUndecorated(true);
        setResizable(false);

        pnlDashBoard.setMaximumSize(new java.awt.Dimension(1900, 963));
        pnlDashBoard.setMinimumSize(new java.awt.Dimension(1900, 963));
        pnlDashBoard.setPreferredSize(new java.awt.Dimension(1900, 963));
        pnlDashBoard.setLayout(null);

        pnlShowNewMember.setBackground(new java.awt.Color(255, 196, 40));

        lblNewMemberTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNewMemberTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblNewMemberTitle.setText("New Member");

        lblNewMemberName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNewMemberName.setForeground(new java.awt.Color(0, 0, 0));
        lblNewMemberName.setText("Emma Stone");

        lblIconNewMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/member.png"))); // NOI18N

        javax.swing.GroupLayout pnlShowNewMemberLayout = new javax.swing.GroupLayout(pnlShowNewMember);
        pnlShowNewMember.setLayout(pnlShowNewMemberLayout);
        pnlShowNewMemberLayout.setHorizontalGroup(
            pnlShowNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowNewMemberLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlShowNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewMemberTitle)
                    .addComponent(lblNewMemberName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIconNewMember)
                .addGap(31, 31, 31))
        );
        pnlShowNewMemberLayout.setVerticalGroup(
            pnlShowNewMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowNewMemberLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblNewMemberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblNewMemberName)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowNewMemberLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblIconNewMember)
                .addGap(36, 36, 36))
        );

        pnlDashBoard.add(pnlShowNewMember);
        pnlShowNewMember.setBounds(80, 320, 330, 220);

        pnlShowRevenue.setBackground(new java.awt.Color(255, 196, 40));

        lblRevenueTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRevenueTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblRevenueTitle.setText("Revenue");

        lblRevenue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRevenue.setForeground(new java.awt.Color(0, 0, 0));
        lblRevenue.setText("2,00,000");

        lblIconMoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/money.png"))); // NOI18N

        javax.swing.GroupLayout pnlShowRevenueLayout = new javax.swing.GroupLayout(pnlShowRevenue);
        pnlShowRevenue.setLayout(pnlShowRevenueLayout);
        pnlShowRevenueLayout.setHorizontalGroup(
            pnlShowRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowRevenueLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pnlShowRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevenue))
                .addGap(40, 40, 40)
                .addComponent(lblIconMoney)
                .addGap(32, 32, 32))
        );
        pnlShowRevenueLayout.setVerticalGroup(
            pnlShowRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowRevenueLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblRevenue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowRevenueLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblIconMoney)
                .addGap(59, 59, 59))
        );

        pnlDashBoard.add(pnlShowRevenue);
        pnlShowRevenue.setBounds(530, 320, 330, 220);

        pnlShowTotalMember.setBackground(new java.awt.Color(255, 196, 40));

        lblTotalMemberTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalMemberTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalMemberTitle.setText("Total Members");

        lblTotalMember.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalMember.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalMember.setText("265");

        lblTotalMemberIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/totalMember.png"))); // NOI18N

        javax.swing.GroupLayout pnlShowTotalMemberLayout = new javax.swing.GroupLayout(pnlShowTotalMember);
        pnlShowTotalMember.setLayout(pnlShowTotalMemberLayout);
        pnlShowTotalMemberLayout.setHorizontalGroup(
            pnlShowTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowTotalMemberLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlShowTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalMemberTitle)
                    .addComponent(lblTotalMember, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalMemberIcon)
                .addGap(42, 42, 42))
        );
        pnlShowTotalMemberLayout.setVerticalGroup(
            pnlShowTotalMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowTotalMemberLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTotalMemberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalMember)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowTotalMemberLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lblTotalMemberIcon)
                .addGap(41, 41, 41))
        );

        pnlDashBoard.add(pnlShowTotalMember);
        pnlShowTotalMember.setBounds(1450, 320, 330, 220);

        pnlShowUPcomingEvents.setBackground(new java.awt.Color(255, 196, 40));

        lblUpcomingEventTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUpcomingEventTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblUpcomingEventTitle.setText("Upcoming Event");

        lblEventName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEventName.setForeground(new java.awt.Color(0, 0, 0));
        lblEventName.setText("Classic Physique");

        lblEventIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/event.png"))); // NOI18N

        javax.swing.GroupLayout pnlShowUPcomingEventsLayout = new javax.swing.GroupLayout(pnlShowUPcomingEvents);
        pnlShowUPcomingEvents.setLayout(pnlShowUPcomingEventsLayout);
        pnlShowUPcomingEventsLayout.setHorizontalGroup(
            pnlShowUPcomingEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUPcomingEventsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlShowUPcomingEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpcomingEventTitle)
                    .addComponent(lblEventName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEventIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlShowUPcomingEventsLayout.setVerticalGroup(
            pnlShowUPcomingEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUPcomingEventsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUpcomingEventTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblEventName)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlShowUPcomingEventsLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblEventIcon)
                .addGap(53, 53, 53))
        );

        pnlDashBoard.add(pnlShowUPcomingEvents);
        pnlShowUPcomingEvents.setBounds(990, 320, 330, 220);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlDashBoard.add(btnExit);
        btnExit.setBounds(1840, 0, 60, 30);

        lblDashBoardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/dashboardIcon.png"))); // NOI18N
        pnlDashBoard.add(lblDashBoardIcon);
        lblDashBoardIcon.setBounds(0, 0, 2282, 957);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Event handler for the exit button. Exits the application when the user
     * clicks the exit button. Closes the application window and terminates the
     * program.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblDashBoardIcon;
    private javax.swing.JLabel lblEventIcon;
    private javax.swing.JLabel lblEventName;
    private javax.swing.JLabel lblIconMoney;
    private javax.swing.JLabel lblIconNewMember;
    private javax.swing.JLabel lblNewMemberName;
    private javax.swing.JLabel lblNewMemberTitle;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblRevenueTitle;
    private javax.swing.JLabel lblTotalMember;
    private javax.swing.JLabel lblTotalMemberIcon;
    private javax.swing.JLabel lblTotalMemberTitle;
    private javax.swing.JLabel lblUpcomingEventTitle;
    private javax.swing.JPanel pnlDashBoard;
    private javax.swing.JPanel pnlShowNewMember;
    private javax.swing.JPanel pnlShowRevenue;
    private javax.swing.JPanel pnlShowTotalMember;
    private javax.swing.JPanel pnlShowUPcomingEvents;
    // End of variables declaration//GEN-END:variables
}
