package com.gym.view;

/**
 *
 * @author Anish Shrestha 23048634
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    AdminPanel addMember;
    DashBoard dashboard;

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHomeMain = new javax.swing.JPanel();
        btnLearnMore = new javax.swing.JButton();
        btnJoinNow = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblHomeIcon = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menuDashboard = new javax.swing.JMenu();
        menuAdminPanel = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 5));
        setMaximumSize(new java.awt.Dimension(1900, 1000));
        setMinimumSize(new java.awt.Dimension(1900, 1000));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1900, 1000));
        setResizable(false);

        pnlHomeMain.setBackground(new java.awt.Color(0, 0, 0));
        pnlHomeMain.setMaximumSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setMinimumSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setPreferredSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setLayout(null);

        btnLearnMore.setBackground(new java.awt.Color(255, 0, 0));
        btnLearnMore.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnLearnMore.setText("Learn More");
        btnLearnMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnMoreActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnLearnMore);
        btnLearnMore.setBounds(960, 670, 160, 50);

        btnJoinNow.setBackground(new java.awt.Color(255, 0, 0));
        btnJoinNow.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnJoinNow.setText("Join Now");
        btnJoinNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJoinNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinNowActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnJoinNow);
        btnJoinNow.setBounds(1160, 670, 160, 50);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnExit);
        btnExit.setBounds(1850, 20, 60, 30);

        lblHomeIcon.setBackground(new java.awt.Color(51, 51, 51));
        lblHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/home.png"))); // NOI18N
        pnlHomeMain.add(lblHomeIcon);
        lblHomeIcon.setBounds(0, 0, 2502, 1110);

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));

        menuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/dasboard.png"))); // NOI18N
        menuDashboard.setText("DashBoard");
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
        });
        MenuBar.add(menuDashboard);

        menuAdminPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/new member.png"))); // NOI18N
        menuAdminPanel.setText("Admin Panel");
        menuAdminPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAdminPanelMouseClicked(evt);
            }
        });
        MenuBar.add(menuAdminPanel);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHomeMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHomeMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event handler for the Admin Panel menu click event. Opens the Admin Panel
     * if it is not already visible, or brings the existing Admin Panel window
     * to the front if it is already open.
     *
     * @param evt The MouseEvent triggered by the menu item click.
     */
    private void menuAdminPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAdminPanelMouseClicked
        // TODO add your handling code here:      
        if (addMember == null || !addMember.isVisible()) {
            addMember = new AdminPanel();
            addMember.setVisible(true);
        } else {
            addMember.toFront(); // Bring the existing window to the front
        }
    }//GEN-LAST:event_menuAdminPanelMouseClicked
    /**
     * Event handler for the "Learn More" button click event. Triggers a mouse
     * click on the Dashboard menu, simulating a click to navigate to the
     * Dashboard page.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnLearnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnMoreActionPerformed
        // TODO add your handling code here:
        java.awt.event.MouseEvent mouseEvent = new java.awt.event.MouseEvent(
                this, // Source component
                java.awt.event.MouseEvent.MOUSE_CLICKED, // Event type
                System.currentTimeMillis(), // When the event occurred
                0, // No modifiers (e.g., no Ctrl, Alt)
                0, 0, // X and Y coordinates (irrelevant in this case)
                1, // Click count
                false
        );
        menuDashboardMouseClicked(mouseEvent);
    }//GEN-LAST:event_btnLearnMoreActionPerformed
    /**
     * Event handler for the "Join Now" button click event. Triggers a mouse
     * click on the Admin Panel menu, simulating a click to navigate to the
     * Admin Panel page.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnJoinNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinNowActionPerformed
        // TODO add your handling code here:
        java.awt.event.MouseEvent mouseEvent = new java.awt.event.MouseEvent(
                this, // Source component
                java.awt.event.MouseEvent.MOUSE_CLICKED, // Event type
                System.currentTimeMillis(), // When the event occurred
                0, // No modifiers (e.g., no Ctrl, Alt)
                0, 0, // X and Y coordinates (irrelevant in this case)
                1, // Click count
                false // Not a popup trigger
        );
        menuAdminPanelMouseClicked(mouseEvent);
    }//GEN-LAST:event_btnJoinNowActionPerformed
    /**
     * Event handler for the Dashboard menu click event. Opens the Dashboard if
     * it is not already visible, or brings the existing Dashboard window to the
     * front if it is already open.
     *
     * @param evt The MouseEvent triggered by the menu item click.
     */
    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        // TODO add your handling code here:
        if (dashboard == null || !dashboard.isVisible()) {
            dashboard = new DashBoard(); // Create a new instance of DashBoard
            dashboard.setVisible(true);  // Make it visible
        } else {
            dashboard.toFront(); // Bring the existing instance to the front
        }
    }//GEN-LAST:event_menuDashboardMouseClicked
    /**
     * Event handler for the "Exit" button click event. Closes the application
     * by calling System.exit(0), terminating the program.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoinNow;
    private javax.swing.JButton btnLearnMore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHomeIcon;
    private javax.swing.JMenu menuAdminPanel;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JPanel pnlHomeMain;
    // End of variables declaration//GEN-END:variables
}
