package com.gym.view;

/**
 * <b>Home Screen for the Gym Management System</b>
 *
 * <p>
 * The Home class represents the main entry screen of the application, providing
 * users with options to navigate to other parts of the system.</p>
 *
 * <p>
 * Features include:</p>
 * <ul>
 * <li>Navigation buttons to the Admin Panel ("Learn More" and "Join Now").</li>
 * <li>An "Exit" button to close the application.</li>
 * <li>Custom-designed layout for a professional UI experience.</li>
 * </ul>
 *
 * <p>
 * Note: This class manages a single instance of the AdminPanel and ensures
 * proper visibility toggling between the Home and AdminPanel screens.</p>
 *
 * @author Anish Shrestha 23048634
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private final AdminPanel adminPanel = new AdminPanel();

    public Home() {
        initComponents();
        adminPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHomeMain = new javax.swing.JPanel();
        btnLearnMore = new javax.swing.JButton();
        btnJoinNow = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblHomeIcon = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 5));
        setMaximumSize(new java.awt.Dimension(1900, 962));
        setMinimumSize(new java.awt.Dimension(1900, 962));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1900, 962));
        setResizable(false);

        pnlHomeMain.setBackground(new java.awt.Color(0, 0, 0));
        pnlHomeMain.setMaximumSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setMinimumSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setPreferredSize(new java.awt.Dimension(1900, 963));
        pnlHomeMain.setLayout(null);

        btnLearnMore.setBackground(new java.awt.Color(255, 0, 0));
        btnLearnMore.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnLearnMore.setText("Learn More");
        btnLearnMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLearnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnMoreActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnLearnMore);
        btnLearnMore.setBounds(960, 670, 160, 50);

        btnJoinNow.setBackground(new java.awt.Color(255, 0, 0));
        btnJoinNow.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnJoinNow.setText("Join Now");
        btnJoinNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJoinNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinNowActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnJoinNow);
        btnJoinNow.setBounds(1160, 670, 160, 50);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlHomeMain.add(btnExit);
        btnExit.setBounds(1850, 20, 60, 30);

        lblHomeIcon.setBackground(new java.awt.Color(51, 51, 51));
        lblHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/home.png"))); // NOI18N
        pnlHomeMain.add(lblHomeIcon);
        lblHomeIcon.setBounds(0, 0, 2502, 1110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHomeMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlHomeMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for the "Learn More" button. Opens the AdminPanel window
     * and hides the current window.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnLearnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnMoreActionPerformed
        adminPanel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLearnMoreActionPerformed
    /**
     * Event handler for the "Join Now" button click event. Displays the
     * AdminPanel window and hides the current window, allowing the user to
     * transition to the member management interface.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnJoinNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinNowActionPerformed
        adminPanel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnJoinNowActionPerformed

    /**
     * Event handler for the "Exit" button click event. Closes the application
     * by calling System.exit(0), terminating the program.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnJoinNow;
    private javax.swing.JButton btnLearnMore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHomeIcon;
    private javax.swing.JPanel pnlHomeMain;
    // End of variables declaration//GEN-END:variables
}
