// Package declaration for the Gym System views
package com.gym.view;

/**
 *
 * @author Anish Shrestha 23048634
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lblLoginIncorrectPassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lblLoginIncorrectPassword = new javax.swing.JLabel();
        ckLoginShowPassword = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        pfLoginPassword = new javax.swing.JPasswordField();
        tfLoginEmail = new javax.swing.JTextField();
        lblLoginEmail = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(480, 230));
        setMaximumSize(new java.awt.Dimension(900, 525));
        setMinimumSize(new java.awt.Dimension(900, 525));
        setUndecorated(true);
        setResizable(false);

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0));
        pnlLogin.setMaximumSize(new java.awt.Dimension(900, 525));
        pnlLogin.setMinimumSize(new java.awt.Dimension(900, 525));
        pnlLogin.setName(""); // NOI18N
        pnlLogin.setPreferredSize(new java.awt.Dimension(900, 525));
        pnlLogin.setLayout(null);

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlLogin.add(btnExit);
        btnExit.setBounds(0, 10, 60, 30);

        lblLoginIncorrectPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginIncorrectPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoginIncorrectPassword.setForeground(new java.awt.Color(204, 0, 0));
        lblLoginIncorrectPassword.setText("Incorrect Username or Password");
        pnlLogin.add(lblLoginIncorrectPassword);
        lblLoginIncorrectPassword.setBounds(140, 370, 218, 30);

        ckLoginShowPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckLoginShowPassword.setForeground(new java.awt.Color(0, 0, 0));
        ckLoginShowPassword.setText("Show Password");
        ckLoginShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLoginShowPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(ckLoginShowPassword);
        ckLoginShowPassword.setBounds(220, 330, 130, 30);

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(130, 330, 76, 31);
        pnlLogin.add(pfLoginPassword);
        pfLoginPassword.setBounds(130, 270, 210, 40);

        tfLoginEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlLogin.add(tfLoginEmail);
        tfLoginEmail.setBounds(130, 190, 210, 40);

        lblLoginEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLoginEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginEmail.setText("Email");
        pnlLogin.add(lblLoginEmail);
        lblLoginEmail.setBounds(130, 160, 43, 22);

        lblLoginPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLoginPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginPassword.setText("Password");
        pnlLogin.add(lblLoginPassword);
        lblLoginPassword.setBounds(130, 240, 72, 22);

        lblLoginTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Velocity");
        pnlLogin.add(lblLoginTitle);
        lblLoginTitle.setBounds(100, 70, 330, 48);

        lblLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gym/resource/LoginImage.png"))); // NOI18N
        lblLoginImage.setText("jLabel1");
        pnlLogin.add(lblLoginImage);
        lblLoginImage.setBounds(30, 0, 900, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pnlLogin.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Event handler for the login button. Validates the entered email and
     * password. If they match the predefined values, the user is redirected to
     * the Home screen. If the credentials are incorrect, an error message is
     * displayed.
     *
     * @param evt The ActionEvent triggered by the login button click.
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (tfLoginEmail.getText().equals("admin") && pfLoginPassword.getText().equals("admin")) {
            setVisible(false);
            new Home().setVisible(true);
        } else {
            lblLoginIncorrectPassword.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    /* Event handler for the checkbox to show or hide the password.
 * If the checkbox is selected, the password field will display the entered password
 * as plain text. If unselected, the password will be masked with asterisks.
 * @param evt The ActionEvent triggered by the checkbox click.
     */
    private void ckLoginShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLoginShowPasswordActionPerformed
        // TODO add your handling code here:
        if (ckLoginShowPassword.isSelected()) {
            pfLoginPassword.setEchoChar((char) 0);
        } else {
            pfLoginPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ckLoginShowPasswordActionPerformed
    /**
     * Event handler for the exit button. Exits the application when the user
     * clicks the exit button. Closes the application window and terminates the
     * program.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox ckLoginShowPassword;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginImage;
    private javax.swing.JLabel lblLoginIncorrectPassword;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JPasswordField pfLoginPassword;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField tfLoginEmail;
    // End of variables declaration//GEN-END:variables
}
